updated ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,17 +21,24 @@ jobs:
       with:
         php-version: '7.4'
 
-    - name: Install PHP dependencies
-      run: composer install
-
     - name: Set up Node.js
       uses: actions/setup-node@v2
       with:
         node-version: '22.3.0'
 
+    - name: Check for composer.json
+      run: |
+        if [ ! -f composer.json ]; then
+          echo "composer.json not found!"
+          exit 1
+        fi
+  
+    - name: Install PHP dependencies
+      run: composer install
+
     - name: Install Node.js dependencies
       run: npm install
-
+        
     - name: Build CSS with Tailwind
       run: npm run watch:css
 
